import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "@/styles/globals.css";
import { AppNavBar } from "@/components/app/AppNavBar";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoSans.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        <AppNavBar />
        {children}
      </body>
    </html>
  );
}
